spring:
  http:
    encoding:
      charset: UTF-8
      enable : true
      force : true
  config:
    import: classpath:/database.yml
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate :
      #ddl-auto: create  # update #create
      ddl-auto: update
    show-sql : true
    properties :
      hibernate.format_sql : true
