//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemiProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MEGADB : DbContext
    {
        public MEGADB()
            : base("name=MEGADB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch2> Branch2 { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SellOrRefund> SellOrRefunds { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Work> Works { get; set; }
    }
}
