--insert into Branch2(Name, Address, Tel) values(N'1타타대우상용차신협',N'전라북도 군산시 동장산로 172, (소룡동)','063-469-3116');
insert into Branch2(Name, Address, Tel) values(N'2타타대우상용차신협',N'전라북도 군산시 동장산로 172, (소룡동) 1층','063-469-3121');
insert into Branch2(Name, Address, Tel) values(N'419사거리점',N'서울특별시 강북구 삼양로139길 8, (우이동)','02-902-9990');
insert into Branch2(Name, Address, Tel) values(N'63빌딩점',N'서울특별시 영등포구 63로 50, 하(여의도동)','02-780-6535');
insert into Branch2(Name, Address, Tel) values(N'6공단1호점',N'인천광역시 남구 장고개로 48 믿음슈퍼','032-866-1112');
insert into Branch2(Name, Address, Tel) values(N'6공단2호점',N'인천광역시 남구 염전로 241',null);
insert into Branch2(Name, Address, Tel) values(N'7번국도점',N'경상북도 울진군 후포면 후포삼율로 260, (후포리)','054-787-6011');
insert into Branch2(Name, Address, Tel) values(N'88체육관점',N'서울특별시 강서구 공항대로 376, 체육관 1체육관 內(화곡동) 1층','02-2697-5544');
insert into Branch2(Name, Address, Tel) values(N'AK수원점',N'경기도 수원시 팔달구 덕영대로 924, 수원민자역사제 1호 외 11필지(매산로1가)',null);
insert into Branch2(Name, Address, Tel) values(N'CK양평점',N'서울특별시 영등포구 영등포로3길 16','02-2676-5906');
insert into Branch2(Name, Address, Tel) values(N'C골드레이크CC힐점',N'전라남도 나주시 남평읍 나주호로 442-129 골드레이크CC (우산리) 골드레이크CC',null);
insert into Branch2(Name, Address, Tel) values(N'C광주물류센터1호점',N'경기도 광주시 초월읍 경충대로 1337-53 (대쌍령리)',null);
insert into Branch2(Name, Address, Tel) values(N'C광주물류센터2호점',N'경기도 광주시 초월읍 경충대로 1337-21 (대쌍령리)',null);
insert into Branch2(Name, Address, Tel) values(N'C구미도량셀모바일점',N'경상북도 구미시 송동로 87 (도량동)',null);
insert into Branch2(Name, Address, Tel) values(N'C군산문화셀모바일점',N'전라북도 군산시 문화로 95 (수송동)',null);
insert into Branch2(Name, Address, Tel) values(N'C김포아시아나격납고',N'서울특별시 강서구 하늘길 111 국내선주차대기실 (공항동) 국내선주차대기실',null);
insert into Branch2(Name, Address, Tel) values(N'C논산중앙셀모바일점',N'충청남도 논산시 중앙로 383 (취암동)',null);
insert into Branch2(Name, Address, Tel) values(N'C놀다가게강남점',N'서울특별시 강남구 강남대로94길 10 (역삼동)',null);
insert into Branch2(Name, Address, Tel) values(N'C다산베아채CC다산점',N'전라남도 강진군 학장용산길 101 (도암면) 그늘집(다산)',null);
insert into Branch2(Name, Address, Tel) values(N'C다산베아채CC베아채',N'전라남도 강진군 학장용산길 101 (도암면) 그늘집(베아채)',null);
insert into Branch2(Name, Address, Tel) values(N'C다산베아채CC장보고',N'전라남도 강진군 학장용산길 101 (도암면) 학장용산길 101 그늘집(장보고)',null);
insert into Branch2(Name, Address, Tel) values(N'C대구명곡셀모바일점',N'대구광역시 달성군 화원읍 명천로 242 (명곡리)',null);
insert into Branch2(Name, Address, Tel) values(N'C대구상인셀모바일점',N'대구광역시 달서구 상화로 201 (상인동)',null);
insert into Branch2(Name, Address, Tel) values(N'C대한통운김포터미널',N'경기도 김포시 아라육로152번길 115(고촌읍)',null);
insert into Branch2(Name, Address, Tel) values(N'C목포연산셀모바일점',N'전라남도 목포시 산정로 283 메인1번가 (연산동) 메인1번가',null);
insert into Branch2(Name, Address, Tel) values(N'C안성석정셀모바일점',N'경기도 안성시 중앙로 359 (석정동)',null);
insert into Branch2(Name, Address, Tel) values(N'C여미지식물원점',N'제주특별자치도 서귀포시 중문관광로 93 (색달동)',null);
insert into Branch2(Name, Address, Tel) values(N'C오산대원셀모바일점',N'경기도 오산시 대원로 22 (원동)',null);
insert into Branch2(Name, Address, Tel) values(N'C오창과학산업단지점',N'충청북도 청주시 흥덕구 옥산면 과학산업4로 151-5 (남촌리)',null);
insert into Branch2(Name, Address, Tel) values(N'C울산효성공장2호점',N'울산광역시 남구 납도로 30 효성(주) (매암동) 효성(주)',null);
insert into Branch2(Name, Address, Tel) values(N'C원주무실셀모바일점',N'강원도 원주시 무실로 189 (명륜동)',null);
insert into Branch2(Name, Address, Tel) values(N'C이천증포셀모바일점',N'경기도 이천시 이섭대천로 1443 (증포동)',null);
insert into Branch2(Name, Address, Tel) values(N'C익산인화셀모바일점',N'전라북도 익산시 서동로 25 디지털프라자인화점 (인화동2가) 디지털프라자인화점',null);
insert into Branch2(Name, Address, Tel) values(N'C제주대첨단캠퍼스점',N'제주특별자치도 제주시 첨단로8길 40 (아라일동)',null);
insert into Branch2(Name, Address, Tel) values(N'C청주교육대학교점',N'충청북도 청주시 서원구 청남로 2067 청주교대부설초등학교 (수곡동) 청주교대부설초등학교',null);
insert into Branch2(Name, Address, Tel) values(N'C탑스테이볼링장1호점',N'대전광역시 동구 중앙로200번길 66 (원동)','010-3449-3618');
insert into Branch2(Name, Address, Tel) values(N'C탑스테이볼링장2호점',N'대전광역시 동구 중앙로200번길 66 (원동)','010-3449-3618');
insert into Branch2(Name, Address, Tel) values(N'C평택합정셀모바일점',N'경기도 평택시 서동대로 3708 (합정동)',null);
insert into Branch2(Name, Address, Tel) values(N'C포항양덕셀모바일점',N'경상북도 포항시 북구 천마로 105 (양덕동)',null);
insert into Branch2(Name, Address, Tel) values(N'C한국지엠창원공장2호',N'경상남도 창원시 성산구 창원대로 1124 한국지엠창원공장2호점',null);
insert into Branch2(Name, Address, Tel) values(N'C헬로네이처곤지암점',N'경기도 광주시 곤지암읍 신대길 134-14 (신대리)',null);
insert into Branch2(Name, Address, Tel) values(N'C화도DC점',N'경기도 남양주시 화도읍 폭포로 137-45 화도물류센터 (창현리) 화도물류센터',null);
insert into Branch2(Name, Address, Tel) values(N'E1제천충전소점',N'충청북도 제천시 내토로 728 (장락동)',null);
insert into Branch2(Name, Address, Tel) values(N'EBS일산사옥점',N'경기도 고양시 일산동구 한류월드로 281, (장항동) 지하1층','02-526-2951');
insert into Branch2(Name, Address, Tel) values(N'ES충주호리조트점',N'충청북도 제천시 수산면 옥순봉로 1248, (능강리)','043-641-0118');
insert into Branch2(Name, Address, Tel) values(N'E가평휴게소서울점',N'경기도 가평군 미사리로 544 (설악면) 설악주유소 1층','031-584-5902');
insert into Branch2(Name, Address, Tel) values(N'E가평휴게소춘천점',N'경기도 가평군 미사리로540번길 51 (설악면) 설악휴게소 1층','031-584-5901');
insert into Branch2(Name, Address, Tel) values(N'E거가대교휴게소가덕',N'부산광역시 강서구 거가대로 2571, (천성동)','070-4050-691');
insert into Branch2(Name, Address, Tel) values(N'E거가대교휴게소거제',N'경상남도 거제시 장목면 거가대로 1068, (율천리)','055-736-2200');
insert into Branch2(Name, Address, Tel) values(N'M신도림역점',N'서울특별시 구로구 새말로 117-21, 구내상가 번호(신도림동)','02-830-5580');
